"""empty message

Revision ID: e63e14a9e0de
Revises: 35e3edcbb19b
Create Date: 2021-07-21 17:07:10.761325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63e14a9e0de'
down_revision = '35e3edcbb19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
