"""empty message

Revision ID: fd250ddf3b90
Revises: 0424cd0eca68
Create Date: 2021-07-14 17:10:27.904396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd250ddf3b90'
down_revision = '0424cd0eca68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_name', sa.String(), nullable=False))
    op.add_column('Show', sa.Column('venue_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_name'], ['name'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'artist_name')
    # ### end Alembic commands ###
